services:
  backend:
    image: pontocerto-backend
    container_name: pontocerto-backend
    build: ./backend
    ports:
      - 127.0.0.1:8080:8080
  db:
    image: pontocerto-db
    container_name: pontocerto-db
    build: ./backend/db
    ports:
      - 127.0.0.1:5432:5432
