FROM docker.io/postgres:17
MAINTAINER goll goll@disroot.org
USER root

ENV LANG C.UTF-8
ENV POSTGRES_DB pontocerto
ENV POSTGRES_HOST_AUTH_METHOD trust

COPY ./schema.sql /schema.sql

RUN <<EOF
cat > /docker-entrypoint-initdb.d/init.sh <<EOS
#!/bin/sh
psql -d pontocerto < /schema.sql
EOS
EOF
